apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: blockwatcher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: blockWatcher
    spec:
      containers:
      - name: grin-pool
        image: grinpool/services:latest
#        command: ["sleep", "99999"]
        command: ["/usr/local/bin/blockWatcher.py"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value:
          # valueFrom:
          #  secretKeyRef:
          #    name: mysql-pass
          #    key: password

