apiVersion: v1
kind: Service
metadata:
  name: grin
  labels:
    app: grin
spec:
  type: LoadBalancer
  ports:
  - port: 13413
    nodePort: 32413
    protocol: TCP
    name: grinapi
  - port: 13414
    nodePort: 32414
    protocol: TCP
    name: grinptop
  - port: 13416
    nodePort: 32416
    protocol: TCP
    name: grinstratum
  selector:
    app: grin
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: grin
spec:
  selector:
    matchLabels:
      app: grin
  serviceName: grin
  replicas: 3
  template:
    metadata:
      labels:
        app: grin
    spec:
      containers:
      - name: grin
        image: grinpool/grin:latest
#        command: ["sleep", "9999"]
        command: ["/run.sh"]
        ports:
        - containerPort: 13413
        - containerPort: 13414
        - containerPort: 13415
        - containerPort: 13416
        volumeMounts:
        - name: grinblockchain
          mountPath: /server
      - name: sharewatcher
        image: grinpool/logstash:latest
        command: ["logstash", "-f", "/usr/share/logstash/config/grinsharefilter.conf"]
#        command: ["sleep", "9999999"]
        volumeMounts: # directory inside container
        - name: grinblockchain
          mountPath: /server
  volumeClaimTemplates:
  - metadata:
      name: grinblockchain
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
