apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: makepayouts
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: makepayouts
            image: grinpool/services:latest
#            command: ["sleep", "999"]
            command: ["/usr/local/bin/makePayouts.py"]
            env:
            - name: MYSQL_ROOT_PASSWORD
              value:
              #valueFrom:
              #  secretKeyRef:
              #    name: mysql-pass
              #    key: password
            volumeMounts:
            - name: grinwallet
              mountPath: /wallet
          volumes:
          - name: grinwallet
            persistentVolumeClaim:
              claimName: grinwallet
          restartPolicy: Never
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
