apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: poolstats
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: poolstats
    spec:
      containers:
      - name: grin-pool
        image: grinpool/services:latest
        command: ["/usr/local/bin/poolStats.py"]
#        command: ["sleep", "99999"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value:
          #valueFrom:
          #  secretKeyRef:
          #    name: mysql-pass
          #    key: password
