---
apiVersion: v1
kind: Service
metadata:
  name: shareaggr
  labels:
    run: shareaggr
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 32080
    protocol: TCP
    name: shareaggr
  selector:
    run: shareaggr
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shareaggr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: shareaggr
    spec:
      containers:
      - name: shareaggr
        image: grinpool/services:latest
        command: ["/usr/local/bin/shareAggr.py"]
#        command: ["sleep", "9999999"]
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_ROOT_PASSWORD
          value:
          #valueFrom:
          #  secretKeyRef:
          #    name: mysql-pass
          #    key: password

