apiVersion: v1
kind: Service
metadata:
  name: stratum
  labels:
    run: stratum
spec:
  type: LoadBalancer
  ports:
  - port: 3333
    nodePort: 32333
    protocol: TCP
  selector:
    run: stratum
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stratum
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: stratum
    spec:
      containers:
      - name: stratum
        image: grinpool/stratum:latest
        command: ["/run.sh"]
        ports:
        - containerPort: 3333
        volumeMounts:
        - name: logdir
          mountPath: /stratum
      - name: sharewatcher
        image: grinpool/logstash:latest
        command: ["logstash", "-f", "/usr/share/logstash/config/poolsharefilter.conf"]
        volumeMounts:
        - name: logdir
          mountPath: /stratum
      volumes:
      - name: logdir
        emptyDir: {}
