apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: workerstats
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: workerstats
    spec:
      containers:
      - name: grin-pool
        image: grinpool/services:latest
        command: ["/usr/local/bin/workerStats.py"]
#        command: ["sleep", "99999"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value:
#          valueFrom:
#            secretKeyRef:
#              name: mysql-pass
#              key: password
