apiVersion: v1
kind: Service
metadata:
  name: grin
  labels:
    run: grin
spec:
  type: LoadBalancer
  ports:
  - port: 13413
    nodePort: 32413
    protocol: TCP
    name: grinapi
  - port: 13414
    nodePort: 32414
    protocol: TCP
    name: grinptop
  - port: 13415
    nodePort: 32415
    protocol: TCP
    name: grinwallet
  - port: 13416
    nodePort: 32416
    protocol: TCP
    name: grinstratum
  selector:
    run: grin
  externalIPs:
  - 192.168.2.224
