apiVersion: v1
kind: Service
metadata:
  name: grinwallet
  labels:
    run: grinwallet
spec:
  type: LoadBalancer
  ports:
  - port: 13415
    nodePort: 32415
    protocol: TCP
    name: grinwallet
  selector:
    run: grinwallet
  externalIPs:
  - 192.168.2.224
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grinwallet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: grinwallet
    spec:
      containers:
      - name: grinwallet
        image: grinpool/grin:latest
#        command: ["sleep", "9999"]
        command: ["/run-wallet.sh"]
        ports:
        - containerPort: 13415
        volumeMounts: # directory inside container
        - mountPath: /wallet
          name: grinwallet
#      imagePullSecrets:
#      - name: regsecret
      volumes: # directory location on host
      - name: grinwallet
        hostPath:
          path: /data/wallet
