apiVersion: v1
kind: Service
metadata:
  name: grin
  labels:
    run: grin
spec:
  type: LoadBalancer
  ports:
  - port: 13413
    nodePort: 32413
    protocol: TCP
    name: grinapi
  - port: 13414
    nodePort: 32414
    protocol: TCP
    name: grinptop
  - port: 13415
    nodePort: 32415
    protocol: TCP
    name: grinwallet
  - port: 13416
    nodePort: 32416
    protocol: TCP
    name: grinstratum
  selector:
    run: grin
  externalIPs:
  - 192.168.2.251
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: grin
    spec:
      containers:
      - name: grin
        image: grinpool/grin:latest
#        command: ["sleep", "9999"]
        command: ["/run.sh"]
        ports:
        - containerPort: 13413
        - containerPort: 13414
        - containerPort: 13415
        - containerPort: 13416
        volumeMounts: # directory inside container
        - mountPath: /server
          name: grinblockchain
#      imagePullSecrets:
#      - name: regsecret
      volumes: # directory location on host
      - name: grinblockchain
        hostPath:
          path: /data/grin
