apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: grin-pool
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      nodePort: 30306
  selector:
    app: grin-pool
    tier: mysql
  externalIPs:
    - 192.168.2.251
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: grin-pool
spec:
  selector:
    matchLabels:
      app: grin-pool
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grin-pool
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: pv0001
          mountPath: /var/lib/mysql
      volumes:
      - name: pv0001
        persistentVolumeClaim:
          claimName: pv0001
