apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: poolsharewatcher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: poolshareWatcher
    spec:
      containers:
      - name: grin-pool
        image: grinpool/services:latest
        command: ["/usr/local/bin/poolshareWatcher.py"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        volumeMounts: # directory inside container
        - mountPath: /stratum
          name: stratumdir
        - mountPath: /services
          name: poolservicesdir
      volumes: # directory location on host
      - name: stratumdir
        hostPath:
          path: /data/stratum
      - name: poolservicesdir
        hostPath:
          path: /data/services
#      imagePullSecrets:
#      - name: regsecret
