---

- name: Deploy ssh public key
  authorized_key:
    user: "{{ admin_user }}"
    state: present
    key: "{{ lookup('file', 'id_rsa.pub') }}"

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add sudoers users to wheel group
  user: name="{{admin_user}}" groups=wheel append=yes state=present createhome=yes

- name: Make sure we have a 'docker' group
  group:
    name: docker
    state: present

- name: Add admin account to the docker group
  user: name="{{admin_user}}" groups=docker append=yes state=present createhome=yes

- name: Kill SSH
  shell: sleep 1; pkill -u {{ ansible_ssh_user }} sshd
  async: 3
  poll: 2
   
#- name: Reboot 
#  shell: sleep 5 && init 6
#  async: 1
#  poll: 0
#
#- name: Wait for the reboot to complete
#  wait_for_connection:
#    connect_timeout: 20
#    sleep: 5
#    delay: 15
#    timeout: 300
