---

- name: Install Docker's dependencies
  apt:
    name: "{{ item }}"
  loop: "{{ docker_package_dependencies }}"

- name: Add Docker's GPG key
  apt_key:
    id: "{{ docker_apt_key_id }}"
    url: "{{ docker_apt_key_server }}"

- name: Configure upstream APT repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"


