---

- name: Install Docker's dependencies
  apt:
    name: "{{ docker_package_dependencies }}"

- name: Add Docker's GPG key
  apt_key:
    id: "{{ docker_apt_key_id }}"
    url: "{{ docker_apt_key_server }}"

- name: Configure upstream APT repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"

- name: Install Docker
  apt:
    name: "docker-{{ docker_edition }}"
    state: "latest"

- name: Restart Docker
  service:
    name: "docker"
    state: "restarted"

- name: Add user(s) to "docker" group
  user:
    name: "{{ admin_user }}"
    groups: "docker"
    append: True

- name: Install docker-py for managing Docker login credentials
  pip:
    name: "docker-py"
