---

- name: Install pip
  apt:
    name: ["python", "python-pip"]

- name: Install Pre-Reqs
  pip:
    name: "docker-py"

- name: Ensure grin data directory exists
  file:
    path: /data/grin
    state: directory
    mode: 0755


- name: Check for pre-canned blockchain tgz
  local_action: stat path={{ role_path }}/files/grin_bc.tgz
  become: no
  register: stat_grinbc

- name: Copy pre-canned blockchain (if one exists)
  copy:
    src: "{{ role_path }}/files/grin_bc.tgz"
    dest: /data/grin
  when: stat_grinbc.stat.exists

- name: Extract the pre-canned blockchain (if one exists)
  shell: tar xzf grin_bc.tgz
  args:
    chdir: /data/grin
  when: stat_grinbc.stat.exists


- name: Pull and start Grin container
  docker_container:
    name: grinwallet
    image: grinpool/grin
    command: "/run-wallet.sh"
    state: started
    pull: true
    ports:
    - "13415:13415"
    etc_hosts:
      grin: "{{ ansible_default_ipv4.address }}"
      grinwallet: "{{ ansible_default_ipv4.address }}"
    volumes:
      - /data/wallet:/wallet

- name: Pull and start Grin Wallet container
  docker_container:
    name: grin
    image: grinpool/grin
    state: started
    command: "/run.sh"
    pull: true
    ports:
    - "13413:13413"
    - "13414:13414"
    - "13416:13416"
    etc_hosts:
      grin: "{{ ansible_default_ipv4.address }}"
      grinwallet: "{{ ansible_default_ipv4.address }}"
    volumes:
      - /data/grin:/server
